<script src="public/js/test/test.js"></script>


<h1>Sr Pago.</h1>


    <style>
       #map {
        height: 400px;
        width: 100%;
       }
    </style>

    <h3>My Google Maps Demo</h3>
    <div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: 19.367, lng: -99.140};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: uluru
        });

        
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBpWaqS6T-xKxKyLg6DAKKrsD5os-3QmbA&callback=initMap">
    </script>
